### ISSUE TITLE
Android Supprt for Delphi

### ISSUE THREAD

**Issue by phomm** [Relfos/TERRA-Engine#11]
Hello
It's written in readme, that Terra has Android support via FPC and Delphi
I've tried to build Terra samples for windows - everything is OK, tried on Android - lots of compilation errors about not working "system" routines like debug, callstack, cmem, unixthreads and so on, main units like terra_object or terra_string are not compilable due to string types unsupported for android target.
Tried some steps like putting conditional defines, commenting some units - still lots of errors.

Please provide info about the way to get Terra running on android, either Delphi(preferably) or FPC (which is way harder to get anything working in android-building toolchain). 

P.S. I'm using Delphi XE7 update1 and do things for android with it (i.e. http://delphioga.sf.net/ even without FMX), tried some FPC-guides for android, but not yet successful (if Terra would support only FPC for Android - it's OK, I'll manage that)
Thank you for Terra, BTW.

**Comment by Relfos** [comment]
TERRA does support Android, I made this game that is published in the Play Store with TERRA + FPC 2.7
(https://play.google.com/store/apps/details?id=com.terra.minimon3d&hl=en)

However let me warn you that it is difficult to get this working, in part due to TERRA being a huge project but also due to FPC support for Android being extremely fragile. As far as I know the only way to currrently getting this to work will be using the "old_master" branch (this is the one that is used in my game and that I can garantee that works fine in Android) and you'll need FPC 2.7 (as far as I know, the 3.0 release changed the way that strings work and other stuff, and broke TERRA in Android).

Also you will need a FPC 2.7 compiled with support for native floating point, this is extremly important, as from what I remembered, the available precompiled binaries were compiled with soft floatiing point emulation, which for games is very bad for performance.

**Comment by Relfos** [comment]
About Delphi, I only use Delphi 7 for compiling in Windows, I dont have access to other versions, so I can't comment much about support.
Some other coders already sent me patches that allows to use TERRA in Delphi XE2 (and possibly others).
